#!/bin/sh
#
# Loop through all refs in a post-receive hook and run podpourri-build.

set -eu

umask 0022

while read -r _ _ REFNAME
do
    # Remove refs/heads/ prefix (if matching).
    BRANCH=${REFNAME#refs/heads/}
    case "${BRANCH}" in
        *[!a-zA-Z0-9-_.]*)
            # Invalid ref name. This is either a tag and thus containing
            # slashes (refs/tags/...) or it is a branch containing characters
            # which are not suitable as container tags. Skipping build.
            ;;
        *)
            PODPOURRI_REPO="${PWD}#${BRANCH}"
            PODPOURRI_JOBTAG_PREFIX="build-push-"

            /usr/bin/env \
                git gau-exec "${PODPOURRI_REPO}" \
                podpourri-tag-xargs "${PODPOURRI_JOBTAG_PREFIX}" -I"{PODPOURRI_JOBTAG}" \
                git gau-at "{PODPOURRI_JOBTAG}" \
                git gau-xargs -I"{WORKDIR}" \
                podpourri-build "{WORKDIR}" podman "{PODPOURRI_JOBTAG}"

            /usr/bin/env \
                git gau-exec "${PODPOURRI_REPO}" \
                podpourri-schedule-systemd systemctl --user
            ;;
    esac
done
