#!/usr/bin/env python3

import sys
import os

if sys.argv[1] == 'image' and sys.argv[2] == 'build':
    print('PODMAN build called with args:', ' '.join(sys.argv[3:]))
elif sys.argv[1] == 'image' and sys.argv[2] == 'pull':
    print('PODMAN pull called with args:', ' '.join(sys.argv[3:]))
elif sys.argv[1] == 'image' and sys.argv[2] == 'push':
    print('PODMAN push called with args:', ' '.join(sys.argv[3:]))
elif sys.argv[1] == 'image' and sys.argv[2] == 'import':
    print('PODMAN import called with args:', ' '.join(sys.argv[3:]))
elif sys.argv[1] == 'image' and sys.argv[2] == 'inspect' and sys.argv[3] == '--format' and sys.argv[4] == '{{.RootFS.Layers}}':
    print(f'[sha256:{os.environ["PODMAN_STUB_SHA256_SUM"]}]')
else:
    sys.exit(1)
