#!/usr/bin/env python3

import sys

if sys.argv[1] == 'image' and sys.argv[2] == 'build':
    print('PODMAN build called with args:', ' '.join(sys.argv[3:]))
elif sys.argv[1] == 'image' and sys.argv[2] == 'push':
    print('PODMAN push called with args:', ' '.join(sys.argv[3:]))
else:
    sys.exit(1)
