---
name: Lint

on:
  push:
    branches:
      - main
      - develop
    tags:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Lint
        run: make lint
