---
name: Unit test

on:
  - push
  - pull_request

jobs:
  unittest:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit test
        run: make python=python3 test
